<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnbXXIO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnbXXIO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMnbXXIO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMnbXXIO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMnbXXIO\App_KernelProdContainer([
    'container.build_hash' => 'MnbXXIO',
    'container.build_id' => '7d57ab95',
    'container.build_time' => 1655805043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnbXXIO');
