<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7223xdW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7223xdW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7223xdW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7223xdW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7223xdW\App_KernelDevDebugContainer([
    'container.build_hash' => '7223xdW',
    'container.build_id' => '94b13a07',
    'container.build_time' => 1664289334,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7223xdW');
